# Generated by Django 4.2.4 on 2023-09-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_appointment_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
    ]
