# Generated by Django 4.2.4 on 2023-09-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_appointment_modified_date_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('not_paid', 'Not_paid'), ('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
