# Generated by Django 4.2.4 on 2023-09-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed')], default='not_paid', max_length=20),
        ),
    ]
