# Generated by Django 4.2.4 on 2023-10-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='order_id',
        ),
    ]
