# Generated by Django 4.2.4 on 2023-10-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_remove_appointment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='not_paid', max_length=20),
        ),
    ]
