# Generated by Django 5.0.1 on 2024-02-07 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_appointment_cancel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='feedback_status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TherapySessionFeedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.CharField(max_length=255, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.appointment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.feedbackquestions')),
            ],
        ),
    ]
