# Generated by Django 5.0.1 on 2024-02-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_feedbackquestions_appointment_feedback_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=20)),
                ('communication', models.CharField(max_length=20)),
                ('understanding', models.CharField(max_length=20)),
                ('comfort', models.CharField(max_length=20)),
                ('techniques', models.CharField(max_length=20)),
                ('recommendation', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
