# Generated by Django 5.0.1 on 2024-03-26 08:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.TimeField(choices=[(datetime.time(9, 0), '09:00 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(13, 0), '01:00 PM'), (datetime.time(15, 0), '03:00 PM'), (datetime.time(17, 0), '05:00 PM'), (datetime.time(14, 0), '02:00 PM')], null=True),
        ),
        migrations.CreateModel(
            name='QuestionnaireOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.questionnairequestions')),
            ],
        ),
    ]
