# Generated by Django 4.2.4 on 2023-08-16 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_userprofile_profile_picture'),
        ('therapist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='therapy',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='therapist',
            name='therapy_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='therapist.therapy'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='therapist',
            name='userprofile_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
