# Generated by Django 4.2.4 on 2023-08-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0002_remove_therapist_therapy_remove_therapist_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='userprofile_id',
        ),
        migrations.AddField(
            model_name='therapist',
            name='certification_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
