# Generated by Django 4.2.4 on 2023-09-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0005_rename_therapy_id_therapist_therapy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='user_profile',
        ),
    ]
