# Generated by Django 4.2.4 on 2023-09-21 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0011_therapistdayoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapist.therapist'),
        ),
    ]
