# Generated by Django 4.2.4 on 2023-09-23 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_appointment_modified_date_alter_appointment_status'),
        ('therapist', '0013_alter_leaverequest_therapist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapySessionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Zoom', 'Zoom'), ('Microsoft Teams', 'Microsoft Teams'), ('Google Meet', 'Google Meet'), ('Skype', 'Skype'), ('Cisco Webex', 'Cisco Webex')], max_length=20)),
                ('meeting_url', models.URLField()),
                ('scheduled_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='therapy_session', to='client.appointment')),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
    ]
