# Generated by Django 4.2.4 on 2023-09-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0014_therapysessionschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapysessionschedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
