# Generated by Django 5.0.1 on 2024-03-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0016_therapy_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='meeting_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='therapysessionschedule',
            name='platform',
            field=models.CharField(choices=[('SoulCure', 'SoulCure')], max_length=20),
        ),
    ]
