# Generated by Django 5.0.1 on 2024-02-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_postview'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
