# Generated by Django 5.0.1 on 2024-03-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_alter_notification_room_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
