# Generated by Django 4.2.4 on 2023-09-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Client'), (2, 'Therapist'), (3, 'Editor'), (4, 'Admin')], default='1', null=True),
        ),
    ]
