# Generated by Django 4.2.4 on 2023-09-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='addressline1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='addressline2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
